#!/usr/bin/env bash
set -x

# Pin to GPUs 1,2
export CUDA_VISIBLE_DEVICES=2,3
unset ROCR_VISIBLE_DEVICES
export PYTHONUNBUFFERED=1
export HYDRA_FULL_ERROR=1
export PYTHONPATH="/home/keaneong/human-behavior/verl:$PYTHONPATH"
export NCCL_ASYNC_ERROR_HANDLING=1

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=/scratch/keane/human_behaviour/human_behaviour_data/fixed_0.1_train.jsonl \
    data.val_files=/scratch/keane/human_behaviour/human_behaviour_data/fixed_0.1_val.jsonl \
    data.train_batch_size=240 \
    data.val_batch_size=120 \
    data.max_prompt_length=4096 \
    data.max_response_length=4096 \
    data.filter_overlong_prompts=False \
    data.truncation='left' \
    data.image_key=images \
    data.video_key=videos \
    data.prompt_key=problem \
    data.dataloader_num_workers=8 \
    data.modalities=\'audio,videos\' \
    data.train_modality_batching.enabled=True \
    data.train_modality_batching.drop_last=True \
    data.val_modality_batching.enabled=True \
    data.val_modality_batching.drop_last=False \
    data.format_prompt=/home/keaneong/human-behavior/verl/examples/format_prompt/default.jinja \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-Omni-7B \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.weight_decay=0 \
    actor_rollout_ref.model.use_remove_padding=False \
    actor_rollout_ref.actor.ppo_mini_batch_size=60 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=1 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=2 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.engine_kwargs.vllm.disable_mm_preprocessor_cache=True \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=True \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=2 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.rollout.max_model_len=4096 \
    actor_rollout_ref.rollout.max_num_batched_tokens=4096 \
    algorithm.use_kl_in_reward=False \
    custom_reward_function.path=/home/keaneong/human-behavior/verl/examples/reward_function/human_behaviour.py \
    custom_reward_function.name=human_behaviour_compute_score_batch \
    reward_model.reward_manager=batch \
    trainer.critic_warmup=0 \
    trainer.logger='["console","wandb"]' \
    trainer.project_name='mixed_modal_verl_hb' \
    trainer.experiment_name='mixed_modal_omni_gpublock_2' \
    trainer.n_gpus_per_node=2 \
    trainer.nnodes=1 \
    trainer.save_freq=10 \
    trainer.val_before_train=False \
    trainer.val_only=False \
    trainer.validation_data_dir=/home/keaneong/human-behavior/verl/examples/grpo_trainer/val_logs_mixed_modal_verl_models_hb_omni_gpus12 \
    trainer.test_freq=5 \
    trainer.total_epochs=5 $@ \
    trainer.default_local_dir=/scratch/keane/human_behaviour/mixed_modal_verl_models_hb_omni_gpublock2