#!/usr/bin/env bash
set -x

# Pin to GPUs 0,1
export CUDA_VISIBLE_DEVICES=0,1
unset ROCR_VISIBLE_DEVICES
export PYTHONUNBUFFERED=1
export HYDRA_FULL_ERROR=1
export PYTHONPATH="/path/to/verl:$PYTHONPATH"
export NCCL_ASYNC_ERROR_HANDLING=1

    python3 -m verl.trainer.main_ppo \
        algorithm.adv_estimator=grpo \
        data.train_files=/path/to/data/human_behaviour_data/final_v8_train_cleaned_2.jsonl \
        data.val_files=/path/to/data/human_behaviour_data/final_v8_val_cleaned.jsonl \
        data.train_batch_size=256 \
        data.val_batch_size=64 \
        data.max_prompt_length=4096 \
        data.max_response_length=4096 \
        data.filter_overlong_prompts=False \
        data.truncation='right' \
        data.image_key=images \
        data.video_key=videos \
        data.prompt_key=problem \
        data.dataloader_num_workers=8 \
        data.modalities=\'audio,videos\' \
        data.train_modality_batching.enabled=True \
        data.train_modality_batching.drop_last=True \
        data.val_modality_batching.enabled=True \
        data.val_modality_batching.drop_last=False \
        data.format_prompt=/path/to/verl/examples/format_prompt/default.jinja \
        actor_rollout_ref.model.path=Qwen/Qwen2.5-Omni-7B \
        actor_rollout_ref.actor.optim.lr=5e-7 \
        actor_rollout_ref.model.use_remove_padding=True \
        actor_rollout_ref.actor.ppo_mini_batch_size=128 \
        actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2 \
        actor_rollout_ref.actor.use_kl_loss=False \
        actor_rollout_ref.actor.kl_loss_coef=0 \
        actor_rollout_ref.actor.kl_loss_type=low_var_kl \
        actor_rollout_ref.actor.entropy_coeff=0 \
        actor_rollout_ref.actor.ulysses_sequence_parallel_size=1 \
        actor_rollout_ref.model.enable_gradient_checkpointing=True \
        actor_rollout_ref.actor.fsdp_config.param_offload=False \
        actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
        actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=2 \
        actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
        actor_rollout_ref.rollout.name=vllm \
        actor_rollout_ref.rollout.engine_kwargs.vllm.disable_mm_preprocessor_cache=False \
        actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
        actor_rollout_ref.rollout.enable_chunked_prefill=False \
        actor_rollout_ref.rollout.enforce_eager=False \
        actor_rollout_ref.rollout.free_cache_engine=True \
        actor_rollout_ref.rollout.n=5 \
        actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=2 \
        actor_rollout_ref.ref.fsdp_config.param_offload=True \
        actor_rollout_ref.rollout.max_model_len=8192 \
        actor_rollout_ref.rollout.max_num_batched_tokens=8192 \
        algorithm.use_kl_in_reward=False \
        custom_reward_function.path=/path/to/verl/examples/reward_function/hb_omnisapiens_v1.py \
        custom_reward_function.name=human_behaviour_compute_score_batch \
        reward_model.reward_manager=batch \
        trainer.critic_warmup=0 \
        trainer.logger='["console","wandb"]' \
        trainer.project_name='human_behavior_atlas' \
        trainer.experiment_name='grpo_hba' \
        trainer.n_gpus_per_node=4 \
        trainer.nnodes=1 \
        trainer.save_freq=50 \
        trainer.val_before_train=False \
        trainer.val_only=False \
        trainer.validation_data_dir=/path/to/data/grpo \
        trainer.test_freq=50 \
        trainer.total_epochs=5 \
        trainer.advantage_save_dir=/path/to/data/grpo/advantages \
        trainer.advantage_plot_freq=15 $@ \
        trainer.default_local_dir=/path/to/data/grpo