# Auto-generated by tools/build_class_counts.py
# Processed 76362 lines
# Generated at: 2025-10-24 16:46:01

from __future__ import annotations

### Dataset-level: {dataset -> {class_label -> count}}
CLASS_COUNT_INFO_DATASET = {'cremad': {'anger': 892, 'happy': 885, 'disgust': 918, 'neutral': 762, 'sad': 870, 'fear': 882}, 'ptsd_in_the_wild': {'no_ptsd': 253, 'ptsd': 253}, 'ravdess': {'neutral': 68, 'calm': 136, 'happy': 136, 'sad': 136, 'angry': 136, 'fearful': 136, 'disgust': 136, 'surprised': 136}, 'mmpsy_depression': {'no_depression': 705, 'depression': 188}, 'mmpsy_anxiety': {'no_anxiety': 797, 'anxiety': 96}, 'tess': {'disgust': 280, 'fear': 280, 'angry': 280, 'pleasant_surprise': 280, 'happy': 280, 'neutral': 280, 'sad': 280}, 'chsimsv2': {'strongly_negative': 693, 'strongly_positive': 418, 'neutral': 318, 'weakly_negative': 617, 'weakly_positive': 676}, 'meld_emotion': {'neutral': 4709, 'surprise': 1205, 'fear': 268, 'sadness': 683, 'joy': 1743, 'disgust': 271, 'anger': 1109}, 'meld_senti': {'neutral': 4709, 'positive': 2334, 'negative': 2945}, 'mmsd': {'true': 239, 'false': 244}, 'mosei_senti': {'positive': 3084, 'weakly_positive': 3946, 'neutral': 3540, 'weakly_negative': 1887, 'highly_negative': 1071, 'negative': 1781, 'highly_positive': 1017}, 'mosei_emotion': {'happy': 3797, 'fear': 85, 'sad': 743, 'anger': 1030, 'disgust': 506, 'surprise': 85}, 'urfunny': {'true': 834, 'false': 875}, 'daicwoz': {'false': 77, 'true': 30}, 'intentqa': {}, 'mimeqa': {}, 'siq2': {}}
