#!/bin/bash

# Configuration: Specify your file paths here
# step file is the file generated by the model's output at a specific training step
# jsonl is the original dataset jsonl file
STEP_FILE="/Users/keane/Desktop/research/human-behavior/data/tarpo_jsonls/final_jsonls/step_500.json"
JSONL_FILE="/Users/keane/Desktop/research/human-behavior/data/tarpo_jsonls/final_jsonls/final_v8_val_cleaned.jsonl"
OUTPUT_FILE="/Users/keane/Desktop/research/human-behavior/data/tarpo_jsonls/merged_output.jsonl"

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Run the Python script
python3 "${SCRIPT_DIR}/compare_reasoning.py" "$STEP_FILE" "$JSONL_FILE" "$OUTPUT_FILE"
