system:
  cuda_visible_devices: "2,3"  # Set to specific GPU IDs, e.g., "0" for single GPU, "0,1" for multi-GPU

data:
  train_file: "/scratch/keane/human_behaviour/human_behaviour_data/0.1_audio_sigs_train_meld.jsonl"
  val_file: "/scratch/keane/human_behaviour/human_behaviour_data/audio_sigs_val_meld.jsonl"
  test_file: "/scratch/keane/human_behaviour/human_behaviour_data/audio_sigs_test_meld.jsonl"
  label_map_path: "/home/keaneong/human-behavior/verl/multi_task_classification/meld_label_map.json"

model:
  tokenizer_name: "Qwen/Qwen2.5-Omni-7B"
  processor_name: "Qwen/Qwen2.5-Omni-7B"
  training_strategy: "lora"  # options: head_only, lora, full
  lora_config:
    r: 16
    alpha: 32
    dropout: 0.1
    target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

train:
  batch_size: 16
  val_batch_size: 16
  lr: 0.001
  epochs: 2
  save_checkpoint_dir: "/scratch/keane/human_behaviour/lora_sft_meld_trial"
  load_checkpoint_path: null
  save_every_n_epochs: 1
  debug_dry_run: false
  validate_every_n_epochs: 1
  early_stopping_patience: 2

dataset_config:
  max_prompt_length: 4096
  modalities: "images,videos,audio"
  prompt_key: "problem"
  image_key: "images"
  video_key: "videos"
  audio_key: "audios"
  label_key: "answer"
  return_multi_modal_inputs: true
  num_workers: 0
  filter_overlong_prompts_workers: 0
  filter_overlong_prompts: false
  truncation: "right"
  format_prompt: "/home/keaneong/human-behavior/verl/examples/format_prompt/default.jinja"

wandb:
  use: true
  project: "omni-classifier"
  entity: null

