#!/usr/bin/env python3
"""Zero-shot transfer of the HealthBench-trained checkpoints to the held-out report
benchmarks (paper_data/stage2/xdom_zeroshot.json, from the cross-domain val-only queue
scripts/self_evolving/eval/xdomain_queue.sh: live web search, in-loop grader). Renders
paper_stage2/tables/xdom.tex; not yet \\input into the paper.

Usage: python3 scripts/self_evolving/analysis/stage2_xdom_table.py [--data ...] [--paper ...]
"""
import argparse
import json
import os

CAPTION = (r"\caption{Zero-shot transfer: the HealthBench-trained checkpoints on the two report "
           r"benchmarks, answering through the web-search tool loop, in-loop grader. No checkpoint "
           r"saw a task from either benchmark.}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="paper_data/stage2")
    ap.add_argument("--paper", default="paper_stage2")
    a = ap.parse_args()
    rows = json.load(open(os.path.join(a.data, "xdom_zeroshot.json")))["rows"]
    L = [r"\begin{table}[h]", r"\begin{center}", CAPTION, r"\label{tab:xdom}", r"\small",
         r"\begin{tabular}{llrr}", r"\toprule", r"Model & Training & ProfBench & PRBench Hard \\", r"\midrule"]
    last_model = None
    for r in rows:
        if last_model and r["model"] != last_model:
            L.append(r"\midrule")
        last_model = r["model"]
        L.append(f"{r['model']} & {r['training']} & {r['profbench']:.3f} & {r['prbench']:.3f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}"]
    out = os.path.join(a.paper, "tables", "xdom.tex")
    open(out, "w").write("% GENERATED by scripts/self_evolving/analysis/stage2_xdom_table.py. Do not edit by hand.\n" + "\n".join(L) + "\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
