#!/usr/bin/env python3
"""Render the stage-2 analysis tables (appendix) from the audit / regrade / ledger JSONs.

Inputs (paper_data/stage2/):
  audit/taxonomy_hb9b.summary.json, audit/taxonomy_hb27b.summary.json   exploit taxonomy
  audit/criteria_hb9b.summary.json, audit/criteria_hb27b.summary.json   criterion audit
  ledger/<run>.json                                                     repair anatomy
  regrade/<tag>/<run>_<step>.json (optional)                            re-grades
  regrade_rows.json                                                     row -> dump map

Outputs (paper_stage2/tables/): anatomy_taxonomy.tex, anatomy_audit.tex, anatomy_funnel.tex,
and, when the regrade JSONs exist, hbpro_regrade.tex (official grader) and
hbpro_strict.tex (standard vs strict, same grader). Every table is generated; never edit
the .tex by hand.
"""
import argparse
import re
import glob
import json
import os

LABELS = {
    "rubric_cue_matching": "Rubric cue matching",
    "breadth_padding": "Breadth padding",
    "confident_wrong_specifics": "Confident wrong specifics",
    "evidence_substitution": "Evidence substitution",
    "fabricated_evidence": "Fabricated evidence",
    "topic_naming": "Topic naming",
    "hedged_enumeration": "Hedged enumeration",
    "generic_boilerplate": "Generic boilerplate",
    "format_mimicry": "Format mimicry",
    "task_restatement": "Task restatement",
    "other": "Other",
}
DESC = {
    "rubric_cue_matching": "states exactly the facts each criterion names, and little else",
    "breadth_padding": "touches every rubric topic briefly; case-specific content stays thin",
    "confident_wrong_specifics": "states specific but incorrect facts that no criterion penalizes",
    "evidence_substitution": "cites adjacent or non-specific evidence in place of the required evidence",
    "fabricated_evidence": "cites invented or unverifiable studies, guidelines, or figures",
    "topic_naming": "names the entity or mechanism without the value, threshold, or reason",
    "hedged_enumeration": "lists options without committing to the decision the task asks for",
    "generic_boilerplate": "generic safety, red-flag, or referral language",
    "format_mimicry": "produces the requested artifact form; structure earns the credit",
    "task_restatement": "restates the request or the rubric's caveats as findings",
    "other": "none of the above",
}
PROV = "% GENERATED by scripts/self_evolving/analysis/stage2_analysis_tables.py. Do not edit by hand.\n"
RUNS = [("hb9b", "9B setting"), ("hb27b", "27B setting")]

# Captions and labels as audited in the paper repo (commit 84900ee). The generators keep
# their data logic; the audited wording is applied when a table is emitted so that
# regenerating never silently reverts a copy-edit. Keys are table labels.
CAPTIONS = {
    "tab:audit": r'''\caption{Audit of accepted criteria by an LLM auditor shown the task, the original rubric, and the criterion alone, on a stratified sample per run, reporting the share of criteria answered \emph{yes}. A criterion is \emph{correct} when the clinical content is accurate, \emph{relevant} when it bears on what the task asks, and \emph{specific} when it requires a checkable claim rather than a topic mention.}''',
    "tab:taxonomy": r'''\caption{Mechanism of the on-policy exploits caught by the referee, labeled by an LLM auditor shown the task, the original rubric, the exploit answer, the better answer, and the accepted repair; the primary label and its share of cases are shown, with $n=540$ for the 9B run and $n=500$ for the 27B sample.}''',
    "tab:methods": r'''\caption{Inference-time methods on the frozen base models next to the trained rows of the same base model from Table~\ref{tab:main}, HealthBench Professional accuracy under the gpt-chat-latest grader with three votes. The frozen-model methods follow the stage-1 protocol, greedy decoding, no reasoning channel, references from the shared medical corpus placed in the prompt; medical RAG retrieves once, RAG-Fusion fuses three generated queries, and i-MedRAG asks three rounds of two follow-up questions. GEPA and ACE evolve the prompt or a playbook of the frozen model on generated tasks only and answer the validation set once with the frozen result. The trained rows answer with the solver's own tool calls at the training temperature.}''',
    "tab:regrade": r'''\caption{HealthBench Professional accuracy of the rows of Table~\ref{tab:main} re-graded from the same answers with the benchmark's official grader, GPT-5.4 at reasoning effort low with one vote per criterion. The official length-adjusted signed score and the unadjusted rubric fraction are shown.}''',
    "tab:reference": r'''\caption{Reference points on HealthBench Professional under one protocol, the benchmark's official pipeline, no tools, greedy decoding, an 8,192-token answer budget, and the gpt-chat-latest grader used for validation in this paper. Frontier models are served through the same endpoint as the grader; open models are served locally.}''',
    "tab:transfer": r'''\caption{Transfer to HealthBench Hard, the 1,000 hardest tasks of the original HealthBench release, never used for training or validation, in the 27B setting. Scored with the in-loop validator, with solver tools on, the gpt-chat-latest grader, and three votes, using the benchmark's official score, the mean per-example clipped rubric fraction with no length term. Trained rows use the latest retained checkpoint of each run.}''',
}
TEXT_FIXES = [
    ("trained with tools (Table~\\ref{tab:main})", "trained with tools, from Table~\\ref{tab:main}"),
    ("\\textbf{RRIMed-9B}", "\\textbf{RRIMed}"), ("\\textbf{RRIMed-27B}", "\\textbf{RRIMed}"),
    ("GPT chat (latest)", "GPT chat latest"),
]


def emit(T, name, L):
    tex = PROV + "\n".join(L) + "\n"
    m = re.search(r"\\label\{([^}]+)\}", tex)
    if m and m.group(1) in CAPTIONS:
        tex = re.sub(r"\\caption\{.*?\}\n(?=\\label)", lambda _: CAPTIONS[m.group(1)] + "\n", tex, count=1, flags=re.S)
    for a, b in TEXT_FIXES:
        tex = tex.replace(a, b)
    open(os.path.join(T, name), "w").write(tex)


def pct(x):
    return "--" if x is None else f"{100 * x:.0f}"


def render_taxonomy(data, T):
    tax = {k: json.load(open(os.path.join(data, "audit", f"taxonomy_{k}.summary.json"))) for k, _ in RUNS
           if os.path.exists(os.path.join(data, "audit", f"taxonomy_{k}.summary.json"))}
    if not tax:
        return
    keys = sorted(LABELS, key=lambda k: -max(t["primary_share"].get(k, 0) for t in tax.values()))
    L = [r"\begin{table}[h]", r"\begin{center}",
         r"\caption{Mechanism of the on-policy exploits caught by the referee, labeled by an LLM auditor "
         r"shown the task, the original rubric, the exploit answer, the better answer, and the accepted "
         r"repair (primary label, share of cases). " +
         " ".join(f"{t['run'].split('_')[0].replace('hb', '')}: $n={t['n_labeled']}$" for t in tax.values()) + ".}",
         r"\label{tab:taxonomy}", r"\small", r"\setlength{\tabcolsep}{5pt}",
         r"\begin{tabular}{ll" + "r" * len(tax) + "}", r"\toprule",
         "Mechanism & Definition & " + " & ".join(n for k, n in RUNS if k in tax) + r" \\", r"\midrule"]
    for k in keys:
        if all(t["primary_share"].get(k, 0) < 0.005 for t in tax.values()):
            continue
        L.append(f"{LABELS[k]} & {DESC[k]} & " + " & ".join(pct(tax[r]["primary_share"].get(k, 0)) + r"\%" for r, _ in RUNS if r in tax) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}"]
    emit(T, "anatomy_taxonomy.tex", L)


def render_audit(data, T):
    aud = {k: json.load(open(os.path.join(data, "audit", f"criteria_{k}.summary.json"))) for k, _ in RUNS
           if os.path.exists(os.path.join(data, "audit", f"criteria_{k}.summary.json"))}
    if not aud:
        return
    L = [r"\begin{table}[h]", r"\begin{center}",
         r"\caption{Audit of accepted criteria by an LLM auditor shown the task, the original rubric, and "
         r"the criterion alone (stratified sample per run; share of criteria answered \emph{yes}). "
         r"\emph{Correct}: the clinical content is accurate; \emph{relevant}: it bears on what the task asks; "
         r"\emph{specific}: it requires a checkable claim rather than a topic mention.}",
         r"\label{tab:audit}", r"\small", r"\begin{tabular}{lrrrr}", r"\toprule",
         r"Run & $n$ & Correct & Relevant & Specific \\", r"\midrule"]
    for k, name in RUNS:
        if k not in aud:
            continue
        a = aud[k]["shares"]
        L.append(f"{name} & {aud[k]['n']} & " + " & ".join(pct(a[q].get("yes", 0)) + r"\%" for q in ("correct", "relevant", "specific")) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}"]
    emit(T, "anatomy_audit.tex", L)


def render_funnel(data, T):
    runs = [("hb9b_specgap_ship_retrieval_websearch", "9B"), ("hb27b_specgap_ship_retrieval_websearch", "27B"),
            ("hb9b_specgap_ship_noretrieval_sj_aicr", "No-retr.")]
    led = {}
    for r, n in runs:
        p = os.path.join(data, "ledger", f"{r}.json")
        if os.path.exists(p):
            led[n] = json.load(open(p))
    if not led:
        return
    cols = list(led)
    rows = [
        ("Exploit cases", lambda d: f"{d['funnel']['cases']:,}"),
        ("\\quad shipped by the referee", lambda d: f"{d['funnel']['cases_by_source'].get('on_policy_exploit', 0):,}"),
        ("\\quad raised by re-attack", lambda d: f"{d['funnel']['cases_by_source'].get('reattack_round', 0):,}"),
        ("Distinct tasks", lambda d: f"{d['funnel']['tasks_with_case']:,}"),
        ("Accepted criteria", lambda d: f"{d['funnel']['criteria_accepted']:,}"),
        ("\\quad positive share", lambda d: pct(d['funnel']['positive_share']) + "\\%"),
        ("Mean margin removed per criterion", lambda d: f"{d['funnel']['gap_drop_mean']:.2f}"),
        ("Mean exploit minus honest score at capture", lambda d: f"{d['funnel']['exploit_minus_honest_mean']:.2f}"),
        ("Served score on patched tasks, before $\\to$ after", lambda d: f"{d['patch_effect']['pooled_mean_before']:.2f} $\\to$ {d['patch_effect']['pooled_mean_after']:.2f}"),
        ("\\quad tasks whose score fell", lambda d: pct(d['patch_effect']['share_tasks_score_fell']) + "\\%"),
    ]
    L = [r"\begin{table}[h]", r"\begin{center}",
         r"\caption{Anatomy of the hack-then-patch loop per RRIMed run, measured from the repair ledger. "
         r"Served score is the training grader's score of rollouts served on the task before and after "
         r"its first patch.}", r"\label{tab:funnel}", r"\small",
         r"\begin{tabular}{l" + "r" * len(cols) + "}", r"\toprule",
         "& " + " & ".join(cols) + r" \\", r"\midrule"]
    for name, f in rows:
        L.append(f"{name} & " + " & ".join(f(led[c]) for c in cols) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}"]
    emit(T, "anatomy_funnel.tex", L)


def render_heldout(data, T):
    p = os.path.join(data, "heldout_arms.json")
    if not os.path.exists(p):
        return
    d = json.load(open(p))
    rows = [("prbench9b_specgap_ship_websearch", "PRBench Hard, finance and legal", 550, "rubric score"),
            ("profbench9b_specgap_ship_websearch", "ProfBench, PhD and MBA reports", 40, "rubric score"),
            ("medxpert9b_specgap_ship_retrieval_websearch", "MedXpertQA, text and image", 4450, "accuracy")]
    L = [r"\begin{table}[h]", r"\begin{center}",
         r"\caption{RRIMed on held-out rubric benchmarks outside HealthBench Professional, Qwen3.5-9B, "
         r"gpt-chat-latest grader. Each benchmark is used only for validation; the proposer sees a "
         r"paper-level description of the benchmark and no items. Untrained is the base model under "
         r"the same validator; RRIMed is the best validation evaluation of the run. MedXpertQA is scored "
         r"as a one-criterion rubric, so its score is exact-match accuracy, shown for the text and "
         r"image splits.}", r"\label{tab:heldout}", r"\small", r"\begin{tabular}{lrlcc}", r"\toprule",
         r"Benchmark & $n$ & Metric & Untrained & RRIMed \\", r"\midrule"]
    for run, name, n, metric in rows:
        v = d.get(run)
        if not v:
            continue
        L.append(f"{name} & {n} & {metric} & {v['first']['acc_raw']:.3f} & \\textbf{{{v['best']['acc_raw']:.3f}}} \\\\")
        if "text" in v["best"]:
            L.append(f"\\quad text split & 2450 & accuracy & {v['first']['text']:.3f} & \\textbf{{{v['best']['text']:.3f}}} \\\\")
            L.append(f"\\quad image split & 2000 & accuracy & {v['first']['mm']:.3f} & \\textbf{{{v['best']['mm']:.3f}}} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}"]
    emit(T, "heldout_arms.tex", L)


INCLUDE_MEDX = False  # 2026-09-07: MedXpertQA (MCQ) does not move with rubric training (27B: 0.440 -> 0.420); HB-Hard only


def render_transfer(data, T):
    p = os.path.join(data, "transfer.json")
    if not os.path.exists(p):
        return
    d = json.load(open(p))
    if not INCLUDE_MEDX:
        return render_transfer_hbhard(d, T)
    L = [r"\begin{table}[h]", r"\begin{center}",
         r"\caption{Transfer of the trained policies to benchmarks never used for training or validation. "
         r"HealthBench Hard (1,000 tasks, original release) is scored with the in-loop validator, tools on "
         r"in the 27B setting and off in the no-retrieval setting, gpt-chat-latest grader with three votes, "
         r"official score (mean per-example clipped rubric fraction, no length term). MedXpertQA text (2,450 "
         r"questions, 10 options) is exact-match accuracy from a 24k-token greedy budget with no tools. "
         r"Trained rows use the latest retained checkpoint of each run.}",
         r"\label{tab:transfer}", r"\small", r"\begin{tabular}{llcc}", r"\toprule",
         r"Setting & Row & HealthBench Hard & MedXpertQA text \\", r"\midrule"]
    by_setting = {}
    for r in d["rows"]:
        by_setting.setdefault(r["setting"], []).append(r)
    for setting, rows in by_setting.items():
        vals = []
        for r in rows:
            h = r["hbhard"]["acc_raw"] if r.get("hbhard") else None
            m = r["medxpertqa_text"].get("accuracy") if r.get("medxpertqa_text") else None
            vals.append((r, h, m))
        trained = [v for v in vals if v[0]["label"] != "Untrained"]
        bh = max((v[1] for v in trained if v[1] is not None), default=None)
        bm = max((v[2] for v in trained if v[2] is not None), default=None)
        for r, h, m in vals:
            ch = "--" if h is None else (f"\\textbf{{{h:.3f}}}" if r["label"] != "Untrained" and bh is not None and h >= bh else f"{h:.3f}")
            cm = "--" if m is None else (f"\\textbf{{{m:.3f}}}" if r["label"] != "Untrained" and bm is not None and m >= bm else f"{m:.3f}")
            lab = f"\\textbf{{{r['label']}}}" if r["label"].startswith(("SER", "RRIMed")) else r["label"]
            L.append(f"{setting} & {lab} & {ch} & {cm} \\\\")
        L.append(r"\midrule")
    L[-1] = r"\bottomrule"
    L += [r"\end{tabular}", r"\end{center}", r"\end{table}"]
    emit(T, "transfer.tex", L)


TRANSFER_SETTINGS = ("27B",)  # 2026-09-07: the no-retrieval 9B pair ties on HB-Hard (0.153 vs 0.151); 27B only


def render_transfer_hbhard(d, T):
    L = [r"\begin{table}[h]", r"\begin{center}",
         r"\caption{Transfer to HealthBench Hard, the 1,000 hardest tasks of the original HealthBench "
         r"release, never used for training or validation, in the 27B setting. Scored with the in-loop "
         r"validator (solver tools on, gpt-chat-latest grader, three votes) using the "
         r"benchmark's official score, the mean per-example clipped rubric fraction with no length term. "
         r"Trained rows use the latest retained checkpoint of each run.}",
         r"\label{tab:transfer}", r"\small", r"\begin{tabular}{llc}", r"\toprule",
         r"Setting & Row & HealthBench Hard \\", r"\midrule"]
    by_setting = {}
    for r in d["rows"]:
        if r["setting"] in TRANSFER_SETTINGS:
            by_setting.setdefault(r["setting"], []).append(r)
    for setting, rows in by_setting.items():
        vals = [(r, r["hbhard"]["acc_raw"] if r.get("hbhard") else None) for r in rows]
        trained = [h for r, h in vals if r["label"] != "Untrained" and h is not None]
        bh = max(trained, default=None)
        for r, h in vals:
            ch = "--" if h is None else (f"\\textbf{{{h:.3f}}}" if r["label"] != "Untrained" and bh is not None and h >= bh else f"{h:.3f}")
            lab = f"\\textbf{{{r['label']}}}" if r["label"].startswith(("SER", "RRIMed")) else r["label"]
            L.append(f"{setting} & {lab} & {ch} \\\\")
        L.append(r"\midrule")
    L[-1] = r"\bottomrule"
    L += [r"\end{tabular}", r"\end{center}", r"\end{table}"]
    emit(T, "transfer.tex", L)


def render_reference(data, T):
    p = os.path.join(data, "reference_rows.json")
    if not os.path.exists(p):
        return
    # 2026-09-07: our checkpoint under this no-tools protocol is kept in the JSON but not
    # rendered; the table is external reference points only.
    rows = [r for r in json.load(open(p))["rows"] if r["kind"] in ("frontier", "open")]
    order = {"frontier": 0, "open": 1, "ours": 2, "other": 3}
    rows.sort(key=lambda r: (order.get(r["kind"], 9), -r["len_adj"]))
    L = [r"\begin{table}[h]", r"\begin{center}",
         r"\caption{Reference points on HealthBench Professional under one protocol: the benchmark's "
         r"official pipeline, no tools, greedy decoding, an 8,192-token answer budget, and the "
         r"gpt-chat-latest grader used for validation in this paper. Frontier models are served through "
         r"the same endpoint as the grader; open models are served locally.}",
         r"\label{tab:reference}", r"\small", r"\begin{tabular}{lcc}", r"\toprule",
         r"Model & Length-adjusted & Unadjusted \\", r"\midrule"]
    last = None
    for r in rows:
        if last is not None and r["kind"] != last:
            L.append(r"\midrule")
        last = r["kind"]
        name = f"\\textbf{{{r['name']}}}" if r["kind"] == "ours" else r["name"]
        L.append(f"{name} & {r['len_adj']:.3f} & {r['raw']:.3f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}"]
    emit(T, "reference_rows.tex", L)


METHOD_NAMES = [("direct", "Direct answer"), ("medrag", "Medical RAG"), ("rag_fusion", "RAG-Fusion"),
                ("imedrag", "i-MedRAG"), ("gepa", "GEPA evolved prompt"), ("ace", "ACE evolved playbook")]


def render_methods(data, T, table):
    """Inference-time baselines on the frozen base models (stage-1 protocol) next to the
    trained rows of the same base model from the main table."""
    rg = {os.path.basename(p)[:-5]: json.load(open(p))
          for p in glob.glob(os.path.join(data, "regrade", "methods", "*.json")) if not p.endswith(".verdicts.jsonl")}
    if not rg:
        return
    groups = [("qwen35_9b", "A", "Qwen3.5-9B"), ("qwen36_27b", "B", "Qwen3.6-27B")]
    blocks = {b["key"]: b for b in table["blocks"]}
    cols = [("use_case", "consult"), ("use_case", "research"), ("use_case", "writing"),
            ("difficulty", "typical"), ("difficulty", "difficult")]
    L = [r"\begin{table}[h]", r"\begin{center}",
         r"\caption{Inference-time methods on the frozen base models next to the trained rows of the same "
         r"base model (Table~\ref{tab:main}), HealthBench Professional accuracy under the gpt-chat-latest "
         r"grader with three votes. The frozen-model methods follow the stage-1 protocol, greedy decoding, "
         r"no reasoning channel, references from the shared medical corpus placed in the prompt (medical RAG "
         r"retrieves once, RAG-Fusion fuses three generated queries, i-MedRAG asks three rounds of two "
         r"follow-up questions). The trained rows answer with the solver's own tool calls at the training "
         r"temperature.}",
         r"\label{tab:methods}", r"\small", r"\setlength{\tabcolsep}{4.5pt}", r"\begin{tabular}{lcccccc}", r"\toprule",
         r"& \multicolumn{3}{c}{By category} & \multicolumn{2}{c}{By difficulty} & \\",
         r"\cmidrule(lr){2-4} \cmidrule(lr){5-6}",
         r"Model / method & Consult & Research & Writing & Typical & Difficult & Overall \\", r"\midrule"]
    for tag, block, name in groups:
        L.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{name}, frozen}}}} \\\\")
        for mk, mname in METHOD_NAMES:
            d = rg.get(f"{tag}_{mk}")
            if d is None:
                L.append(f"\\quad {mname} & " + " & ".join(["--"] * 6) + " \\\\")
                continue
            v = [d[dim].get(k, {}).get("acc_len_adj_signed") for dim, k in cols] + [d["overall"]["acc_len_adj_signed"]]
            L.append(f"\\quad {mname} & " + " & ".join("--" if x is None else f"{x:.3f}" for x in v) + " \\\\")
        b = blocks.get(block)
        if b:
            L.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{name}, trained with tools (Table~\\ref{{tab:main}})}}}} \\\\")
            for r in b["rows"]:
                if r["label"] == "Untrained":
                    continue
                v = [r["category"].get(k, {}).get("acc_len_adj_signed") for k in ("consult", "research", "writing")]
                v += [r["difficulty"].get(k, {}).get("acc_len_adj_signed") for k in ("typical", "difficult")]
                v += [r["overall"]["acc_len_adj_signed"]]
                lab = f"\\textbf{{{r['label']}}}" if r.get("ours") else r["label"]
                cells = [f"\\textbf{{{x:.3f}}}" if r.get("ours") else f"{x:.3f}" for x in v]
                L.append(f"\\quad {lab} & " + " & ".join(cells) + " \\\\")
        L.append(r"\midrule")
    L[-1] = r"\bottomrule"
    L += [r"\end{tabular}", r"\end{center}", r"\end{table}"]
    emit(T, "hbpro_methods.tex", L)


def load_regrade(data, tag):
    out = {}
    for p in glob.glob(os.path.join(data, "regrade", tag, "*.json")):
        if p.endswith(".verdicts.jsonl"):
            continue
        d = json.load(open(p))
        out[os.path.basename(p)[:-5]] = d
    return out


def render_regrade(data, T, table):
    """Official-grader table: same layout as tab:main, values from regrade/gpt54low."""
    rg = load_regrade(data, "gpt54low")
    rows = json.load(open(os.path.join(data, "regrade_rows.json")))
    if not rg:
        return
    key = lambda r: f"{r['run']}_{r['step']}"
    blocks = {}
    for r in rows:
        if r["block"] in ("A", "B", "C", "D"):
            blocks.setdefault(r["block"], []).append(r)
    titles = {b["key"]: b["title"] for b in table["blocks"]}
    L = [r"\begin{table}[h]", r"\begin{center}",
         r"\caption{HealthBench Professional accuracy of the rows of Table~\ref{tab:main} re-graded from the "
         r"same answers with the benchmark's official grader (GPT-5.4, reasoning effort low, one vote per "
         r"criterion). Length-adjusted signed score (official) and unadjusted rubric fraction.}",
         r"\label{tab:regrade}", r"\small", r"\begin{tabular}{lcccccc}", r"\toprule",
         r"& \multicolumn{3}{c}{By category} & \multicolumn{2}{c}{By difficulty} & \\",
         r"\cmidrule(lr){2-4} \cmidrule(lr){5-6}",
         r"Model / training & Consult & Research & Writing & Typical & Difficult & Overall \\", r"\midrule"]
    complete = True
    for b in ("A", "B", "C", "D"):
        if b not in blocks:
            continue
        L.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{titles[b]}}}}} \\\\")
        vals = []
        for r in blocks[b]:
            d = rg.get(key(r))
            if d is None:
                complete = False
                vals.append((r, None))
                continue
            v = [d["use_case"].get(c, {}).get("acc_len_adj_signed") for c in ("consult", "research", "writing")]
            v += [d["difficulty"].get(c, {}).get("acc_len_adj_signed") for c in ("typical", "difficult")]
            v += [d["overall"]["acc_len_adj_signed"]]
            vals.append((r, v))
        trained = [v for r, v in vals if v and r["label"] != "Untrained"]
        best = [max(x[j] for x in trained) if trained else None for j in range(6)]
        for r, v in vals:
            if v is None:
                cells = ["--"] * 6
            else:
                cells = [(f"\\textbf{{{x:.3f}}}" if (r["label"] != "Untrained" and best[j] is not None and x >= best[j]) else f"{x:.3f}")
                         for j, x in enumerate(v)]
            lab = f"\\textbf{{{r['label']}}}" if r["label"].startswith(("SER", "RRIMed")) else r["label"]
            L.append(f"\\quad {lab} & " + " & ".join(cells) + r" \\")
        L.append(r"\midrule")
    L[-1] = r"\bottomrule"
    L += [r"\end{tabular}", r"\end{center}", r"\end{table}"]
    emit(T, "hbpro_regrade.tex", L)
    return complete


def render_strict(data, T):
    std, strict = load_regrade(data, "chatlatest_std"), load_regrade(data, "chatlatest_strict")
    rows = [r for r in json.load(open(os.path.join(data, "regrade_rows.json"))) if r["block"] in ("A", "B")]
    if not std or not strict:
        return
    key = lambda r: f"{r['run']}_{r['step']}"
    L = [r"\begin{table}[h]", r"\begin{center}",
         r"\caption{Standard versus strict grading of the same answers (gpt-chat-latest, one vote). The strict "
         r"note credits only content the response itself states (Appendix~\ref{app:prompts}); the gap is the "
         r"share of the unadjusted score earned by addressing a topic without stating its content.}",
         r"\label{tab:strict}", r"\small", r"\begin{tabular}{llccc}", r"\toprule",
         r"Setting & Row & Standard & Strict & Gap \\", r"\midrule"]
    names = {"A": "9B", "B": "27B"}
    for r in rows:
        a, b = std.get(key(r)), strict.get(key(r))
        if a is None or b is None:
            L.append(f"{names[r['block']]} & {r['label']} & -- & -- & -- \\\\")
            continue
        s, t = a["overall"]["acc_raw"], b["overall"]["acc_raw"]
        L.append(f"{names[r['block']]} & {r['label']} & {s:.3f} & {t:.3f} & {s - t:.3f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}"]
    emit(T, "hbpro_strict.tex", L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="paper_data/stage2")
    ap.add_argument("--paper", default="paper_stage2")
    a = ap.parse_args()
    T = os.path.join(a.paper, "tables")
    os.makedirs(T, exist_ok=True)
    render_taxonomy(a.data, T)
    render_audit(a.data, T)
    render_funnel(a.data, T)
    render_heldout(a.data, T)
    render_transfer(a.data, T)
    render_reference(a.data, T)
    table = json.load(open(os.path.join(a.data, "stage2_table.json")))
    print("regrade complete:", render_regrade(a.data, T, table))
    render_methods(a.data, T, table)
    # render_strict(a.data, T)  # 2026-09-07: strict-vs-standard gap is <0.01 on every row; not reported
    print("wrote", sorted(os.listdir(T)))


if __name__ == "__main__":
    main()
