#!/usr/bin/env python3
"""Frontier models versus our checkpoints on the held-out benchmarks, one instrument.

Every row is graded by scripts/self_evolving/analysis/regrade_hbpro_dumps.py with
gpt-chat-latest and one vote (paper_data/stage2/frontier/grade/<name>.json). The GPT-5.6
rows come from scripts/self_evolving/eval/frontier_tool_eval.py: native tools off, the
solver's own tool(s) and search budget (web search only on the report benchmarks, budget
2 on ProfBench and 4 on PRBench; the medical arm's two tools with budget 2 on MedXpertQA),
three reasoning efforts. Our rows are the arms' validation dumps. Metric: rubric score
(acc_raw_signed) on ProfBench and PRBench Hard, exact-match accuracy on MedXpertQA.
Missing cells stay blank until their grade file exists.

Usage: python3 scripts/self_evolving/analysis/stage2_frontier_table.py
       [--data paper_data/stage2] [--paper paper_stage2]
"""
import argparse
import json
import os

MODELS = [("luna", "GPT-5.6 luna"), ("terra", "GPT-5.6 terra"), ("sol", "GPT-5.6 sol")]
EFFORTS = ["low", "medium", "high"]
# (label, {benchmark: grade-file stem})
OURS = [
    ("Qwen3.5-9B, untrained, same tools",
     {"profbench": "ours_profbench_9b_untrained", "prbench": "ours_prbench_9b_untrained",
      "medx": "ours_medx_9b_untrained", "medxmm": "ours_medxmm_9b_untrained"}),
    ("Qwen3.5-9B, RRI on the benchmark's own description",
     {"profbench": "ours_profbench_9b_rrimed170", "prbench": "ours_prbench_9b_rrimed350",
      "medx": "ours_medx_9b_rrimed180", "medxmm": "ours_medxmm_9b_rrimed180"}),
    ("Qwen3.6-27B, RRI on the medical description, zero-shot",
     {"profbench": "xdom_profbench_27b_ser200", "prbench": "xdom_prbench_27b_ser200"}),
]
BENCH_COLS = [("profbench", "ProfBench"), ("prbench", "PRBench Hard"), ("medx", "MedXpertQA, text"),
              ("medxmm", "MedXpertQA, image")]

CAPTION = (r"\caption{Frontier models against our checkpoints on the held-out benchmarks under one "
           r"grader (gpt-chat-latest, one vote per criterion). The GPT-5.6 models answer through "
           r"the same tool loop as our models, with native tools disabled, the same search budget, "
           r"and the same forced-answer rule when the budget runs out. Rubric score on ProfBench and "
           r"PRBench Hard, exact-match accuracy on the two MedXpertQA splits.}")


def load(data):
    d = os.path.join(data, "frontier", "grade")
    vals = {}
    for f in os.listdir(d) if os.path.isdir(d) else []:
        if f.endswith(".json"):
            o = json.load(open(os.path.join(d, f)))["overall"]
            vals[f[:-5]] = o["acc_raw_signed"]
    return vals


def cell(vals, key):
    v = vals.get(key)
    return "" if v is None else f"{v:.3f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="paper_data/stage2")
    ap.add_argument("--paper", default="paper_stage2")
    a = ap.parse_args()
    vals = load(a.data)
    L = [r"\begin{table}[h]", r"\begin{center}", CAPTION, r"\label{tab:frontier}", r"\small",
         r"\begin{tabular}{llrrrr}", r"\toprule",
         "Model & Reasoning effort & " + " & ".join(c for _, c in BENCH_COLS) + r" \\", r"\midrule"]
    for short, label in MODELS:
        for e in EFFORTS:
            cells = [cell(vals, f"profbench_{short}_{e}"), cell(vals, f"prbench_{short}_{e}"),
                     cell(vals, f"medxtext_{short}_{e}"), cell(vals, f"medxmm_{short}_{e}")]
            L.append(f"{label} & {e} & " + " & ".join(cells) + r" \\")
    L.append(r"\midrule")
    for label, keys in OURS:
        cells = [cell(vals, keys.get(b, "")) for b, _ in BENCH_COLS]
        L.append(f"{label} & -- & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}"]
    out = os.path.join(a.paper, "tables", "frontier.tex")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("% GENERATED by scripts/self_evolving/analysis/stage2_frontier_table.py. Do not edit by hand.\n"
                         + "\n".join(L) + "\n")
    print("wrote", out)
    blanks = [l for l in L if "& " in l and l.endswith(r"\\") and " &  " in l or l.endswith(r"&  \\")]
    print("rows with blank cells:", len(blanks))


if __name__ == "__main__":
    main()
